### ISSUE TITLE
registerBlockExtension Suggestions

### ISSUE THREAD

**Issue by tlovett1** [10up/block-components#215]
A few things on registerBlockExtension:

1) We should add the ability to add arbitrary HTML attributes
2) If classNameGenerator is left out, the extension breaks. It shouldn't require that.

**Comment by fabiankaegy** [comment]
We talked about this a bit in a call last week. The issue here is that I almost regret adding the `inlineStyleGenerator`. The reason why the `registerBlockExtension` API initially only supported classnames is because with classnames it is relatively hard to introduce block deprecations.

If we add anything besides classes it immediately generates block deprecations.

So a better way would be a PHP helper that uses the `HTMLTagProcessor` to add any additional attributes only on the server and a JS helper that only adds it in the editor. Not to the saved markup.

That also automatically gives us support for dynamic blocks. Which is currently not the case with the register block extension API.

**Comment by itsajay1029** [comment]
Can I work on this @tlovett1 @fabiankaegy ?

**Comment by fabiankaegy** [comment]
@itsajay1029 There is currently nothing to be done here. I have to write a quick documentation update. Thank you for reaching out though :)
