### ISSUE TITLE
Content Picker: Support showing an initial set of results on focus

### ISSUE THREAD

**Issue by helen** [10up/block-components#43]
**Is your enhancement related to a problem? Please describe.**
Many content picking scenarios are attempting to select from the latest relevant items. It isn't transparent to the user what to expect once they start typing and they may not even need to search at all.

**Describe the solution you'd like**
Surface an initial X set of results on focus, defaulting to reverse chronological of whatever content is included in search, but I imagine all of this would be configurable via props. IMO it should default to showing those results, with a prop to not show them.

**Designs**
n/a

**Describe alternatives you've considered**
Not an alternative but could consider only showing initial results on focus if nothing has been selected in that picker yet. I am not strongly opinionated on this point at the moment.

**Additional context**
This has been a direct request on other projects and I agree that it is better "starting point" UX. It is not equivalent to core linking, because in that situation there is no real predicting whether a user is trying to make an external or internal content link.

**Comment by xipasduarte** [comment]
Hi. I just added a PR to try and tackle this issue #124. I was searching for a component to do essentially what the `ContentPicker` does, but right upon using it I noticed a potential issue for users. As @helen mentions, this focus results give context to what is being selected/picked/searched.

I went with the approach for only allowing focus results when no results exist, because this addresses the more pressing issue of context. However, I was considering that maybe this initial focus results are more than just the context for what happens when you start typing. As the issue describes the problem "Many content picking scenarios are attempting to select from the latest relevant items." So maybe this should be on always, as it actually saves the user any typing.

Let me know what you think or if there are any other details you feel could be addressed.
